### ISSUE TITLE
Crashes Alongside Magneticraft

### ISSUE THREAD

**Issue by gitgud-software** [CreativeMD/InGameConfigManager#13]
I'm guessing this is a problem with [Magneticraft](https://minecraft.curseforge.com/projects/magneticraft) and not IGCM, but it's worth looking into I guess. If it's not on your end it looks like there's no hope for these two playing nicely; the 1.7.10 version of Magneticraft is officially unmaintained.

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 8/23/16 12:23 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at com.creativemd.ingameconfigmanager.api.common.segment.machine.DisableRecipeSegment.contains(DisableRecipeSegment.java:72)
    at com.creativemd.ingameconfigmanager.api.client.gui.SubGuiBranch.onTick(SubGuiBranch.java:108)
    at com.creativemd.creativecore.common.gui.SubGui.drawForeground(SubGui.java:444)
    at com.creativemd.creativecore.common.gui.GuiContainerSub.func_146979_b(GuiContainerSub.java:145)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.creativemd.ingameconfigmanager.api.common.segment.machine.DisableRecipeSegment.contains(DisableRecipeSegment.java:72)
    at com.creativemd.ingameconfigmanager.api.client.gui.SubGuiBranch.onTick(SubGuiBranch.java:108)
    at com.creativemd.creativecore.common.gui.SubGui.drawForeground(SubGui.java:444)
    at com.creativemd.creativecore.common.gui.GuiContainerSub.func_146979_b(GuiContainerSub.java:145)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
    Screen name: com.creativemd.creativecore.common.gui.GuiContainerSub
    Mouse location: Scaled: (188, 237). Absolute: (753, 53)
    Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['brogrammer'/3645, l='MpServer', x=229.27, y=73.62, z=160.11]]
    Chunk stats: MultiplayerChunkCache: 248, 248
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (236,64,256), Chunk: (at 12,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 12909 game time, 12909 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 31 total; [EntityCow['Cow'/3648, l='MpServer', x=253.50, y=76.00, z=110.47], EntityBat['Bat'/3072, l='MpServer', x=287.25, y=29.10, z=210.25], EntityCow['Cow'/64, l='MpServer', x=159.84, y=82.00, z=202.94], EntityCow['Cow'/3649, l='MpServer', x=253.50, y=76.00, z=111.53], EntityCow['Cow'/3650, l='MpServer', x=255.72, y=76.00, z=107.50], EntityBat['Bat'/3651, l='MpServer', x=304.53, y=19.10, z=128.63], EntityBat['Bat'/3779, l='MpServer', x=267.85, y=26.74, z=188.69], EntitySheep['Sheep'/3652, l='MpServer', x=232.34, y=77.00, z=93.56], EntitySheep['Sheep'/3653, l='MpServer', x=216.38, y=75.00, z=91.72], EntitySheep['Sheep'/3654, l='MpServer', x=222.47, y=74.00, z=94.63], EntityBat['Bat'/3279, l='MpServer', x=220.81, y=40.76, z=217.46], EntitySheep['Sheep'/82, l='MpServer', x=219.38, y=75.00, z=144.53], EntitySheep['Sheep'/83, l='MpServer', x=210.50, y=72.00, z=161.75], EntitySheep['Sheep'/84, l='MpServer', x=212.38, y=73.00, z=149.22], EntitySheep['Sheep'/85, l='MpServer', x=194.34, y=70.00, z=166.50], EntityCow['Cow'/86, l='MpServer', x=214.50, y=66.00, z=207.41], EntityCow['Cow'/87, l='MpServer', x=208.63, y=70.00, z=192.53], EntityCow['Cow'/88, l='MpServer', x=214.50, y=66.00, z=208.53], EntityCow['Cow'/89, l='MpServer', x=217.28, y=71.00, z=202.41], EntityBat['Bat'/3812, l='MpServer', x=174.50, y=53.00, z=131.69], EntityBat['Bat'/3819, l='MpServer', x=169.72, y=39.87, z=109.84], EntityClientPlayerMP['brogrammer'/3645, l='MpServer', x=229.27, y=73.62, z=160.11], EntityCow['Cow'/114, l='MpServer', x=276.50, y=71.00, z=225.50], EntityCow['Cow'/115, l='MpServer', x=275.50, y=76.00, z=225.50], EntityCow['Cow'/116, l='MpServer', x=282.69, y=71.00, z=221.50], EntityBat['Bat'/3508, l='MpServer', x=222.72, y=39.60, z=218.03], EntityCow['Cow'/117, l='MpServer', x=275.19, y=71.00, z=228.19], EntityBat['Bat'/3640, l='MpServer', x=301.49, y=26.85, z=183.34], EntityBat['Bat'/3388, l='MpServer', x=166.16, y=45.79, z=221.90], EntitySheep['Sheep'/3646, l='MpServer', x=209.50, y=79.00, z=96.34], EntityCow['Cow'/3647, l='MpServer', x=253.47, y=76.00, z=115.69]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_102, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 825162672 bytes (786 MB) / 1559232512 bytes (1487 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 46 mods loaded, 46 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCHIJA  CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCHIJA  itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJA  OpenComputers|Core{1.5.22.46} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJA  OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
    UCHIJA  <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJA  FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
    UCHIJA  bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJA  Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJA  CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
    UCHIJA  asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
    UCHIJA  cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
    UCHIJA  ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHIJA  OpenComputers{1.5.22.46} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
    UCHIJA  computronics{1.6.0} [Computronics] (Computronics-1.7.10-1.6.0.jar) 
    UCHIJA  creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
    UCHIJA  Eln{51} [Electrical Age] (ElectricalAge_BETA-1.11_r51.jar) 
    UCHIJA  ExtrabiomesXL{3.16.4} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.4.jar) 
    UCHIJA  flansmod{4.10.0} [Flan's Mod] (Flans Mod Plus-1.7.10-4.10.0-1.0.3.jar) 
    UCHIJA  MapWriter{2.1.1} [MapWriter] (Flans Mod Plus-1.7.10-4.10.0-1.0.3.jar) 
    UCHIJA  ForgeEssentialsClient{1.4.4} [Forge Essentials Client Addon] (forgeessentials-1.7.10-1.4.4.1199-client.jar) 
    UCHIJA  ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHIJA  McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHIJA  hbm{1.0.21} [Hbm's Nuclear Tech Mod] (hbm1.0.21.jar) 
    UCHIJA  IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
    UCHIJA  ingameconfigmanager{0.1} [InGameConfigManager] (InGameConfigManager Alpha v0.1.15 mc1.7.10.zip) 
    UCHIJA  lp{1.0.0} [LightsPlus] (LightsPlus 1.7.10_1.1.0.jar) 
    UCHIJA  Magneticraft{0.6.0-final} [Magneticraft] (magneticraft-0.6.1-final.jar) 
    UCHIJA  neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJA  Netherless{0.9.0} [Netherless] (Netherless-0.9.0.jar) 
    UCHIJA  nnn{1.1} [No Nether Needed] (No Nether Needed 1.1.jar) 
    UCHIJA  neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-122.jar) 
    UCHIJA  OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
    UCHIJA  openmodularturrets{2.2.4-225} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.4-225.jar) 
    UCHIJA  OpenPeripheralCore{1.3} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-7.jar) 
    UCHIJA  OpenPeripheral{0.5.1} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-7.jar) 
    UCHIJA  OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-7.jar) 
    UCHIJA  openprinter{0.1.0.132} [OpenPrinter] (OpenPrinter-MC1.7.10-0.1.0.132.jar) 
    UCHIJA  opensecurity{1.0.91} [OpenSecurity] (OpenSecurity-1.7.10-1.0-91.jar) 
    UCHIJA  pplus{1.7.10} [Peaceful+] (Peaceful Plus [1.7.10].jar) 
    UCHIJA  RealisticTorches{1.6.2} [Realistic Torches] (RealisticTorches-1.7.10-1.6.2.jar) 
    UCHIJA  Sampler{1.60} [Sampler] (sampler-1.60.jar) 
    UCHIJA  territorychevsky{b12} [Territorial Dealings] (TerritorialDealings_1.7.10_b12.zip) 
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4444' Renderer: 'Intel(R) HD Graphics 4600'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@f7cd27a) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@5b74eb67) returned non-null result: 0
    CoFHCore: -[1.7.10]3.1.3-327
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4444, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/143279444857884/172256401838096)

**Comment by CreativeMD** [comment]
Sorry not at home at the moment, but i will take a look at it once i'm back at home.

**Comment by CreativeMD** [comment]
Support for 1.7.10 has been dropped already.
