### ISSUE TITLE
Can Not Create World

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#17]
I can not create new world after installing IGCM. it freezes on "Loading World" screen.
 using minecraft 1.11.2 forge 2259 creative core 1.7.0 and here is the my latest fml latest client log
***i closed game in task maneger***
[fml-client-latest.log.txt](https://github.com/CreativeMD/IGCM/files/853109/fml-client-latest.log.txt)
edit: and i can not load my own world sometimes. (%80 of the time)
please help... thanks.

**Comment by ghost** [comment]
**ah, i found the error part, it is this**
`[12:51:30] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[12:51:30] [Server thread/ERROR] [FML/]: Caught exception from InGameConfigManager (igcm)
java.lang.NullPointerException
	at com.creativemd.igcm.api.machine.ConfigMachineDisableBranch.recipeToString(ConfigMachineDisableBranch.java:76) ~[ConfigMachineDisableBranch.class:?]
	at com.creativemd.igcm.api.machine.ConfigMachineDisableBranch.createChildren(ConfigMachineDisableBranch.java:38) ~[ConfigMachineDisableBranch.class:?]
	at com.creativemd.igcm.api.ConfigBranch.initCore(ConfigBranch.java:27) ~[ConfigBranch.class:?]
	at com.creativemd.igcm.api.machine.ConfigMachineDisableBranch.initCore(ConfigMachineDisableBranch.java:32) ~[ConfigMachineDisableBranch.class:?]
	at com.creativemd.igcm.api.ConfigElement.initCore(ConfigElement.java:47) ~[ConfigElement.class:?]
	at com.creativemd.igcm.api.ConfigBranch.initCore(ConfigBranch.java:28) ~[ConfigBranch.class:?]
	at com.creativemd.igcm.api.ConfigElement.initCore(ConfigElement.java:47) ~[ConfigElement.class:?]
	at com.creativemd.igcm.IGCM.postLoading(IGCM.java:102) ~[IGCM.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:836) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) ~[bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[12:51:30] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from InGameConfigManager (igcm)

Caused by: java.lang.NullPointerException
	at com.creativemd.igcm.api.machine.ConfigMachineDisableBranch.recipeToString(ConfigMachineDisableBranch.java:76) ~[ConfigMachineDisableBranch.class:?]
	at com.creativemd.igcm.api.machine.ConfigMachineDisableBranch.createChildren(ConfigMachineDisableBranch.java:38) ~[ConfigMachineDisableBranch.class:?]
	at com.creativemd.igcm.api.ConfigBranch.initCore(ConfigBranch.java:27) ~[ConfigBranch.class:?]
	at com.creativemd.igcm.api.machine.ConfigMachineDisableBranch.initCore(ConfigMachineDisableBranch.java:32) ~[ConfigMachineDisableBranch.class:?]
	at com.creativemd.igcm.api.ConfigElement.initCore(ConfigElement.java:47) ~[ConfigElement.class:?]
	at com.creativemd.igcm.api.ConfigBranch.initCore(ConfigBranch.java:28) ~[ConfigBranch.class:?]
	at com.creativemd.igcm.api.ConfigElement.initCore(ConfigElement.java:47) ~[ConfigElement.class:?]
	at com.creativemd.igcm.IGCM.postLoading(IGCM.java:102) ~[IGCM.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:836) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) ~[bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[12:51:30] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.`

**Comment by CreativeMD** [comment]
I will try to fix it soon.

**Comment by ghost** [comment]
okay. hopefully waiting.

**Comment by CreativeMD** [comment]
Does this version fix it for you?
https://www.dropbox.com/s/qbrrjr87dw5w7nw/IGCM%20beta%20v1.1.0%20mc1.11.2.zip?dl=1

**Comment by ghost** [comment]
yes it does. thanks!
