### ISSUE TITLE
Invalid smelting recipe registration in Sponge server

### ISSUE THREAD

**Issue by ken1882** [CreativeMD/InGameConfigManager#57]
Log:
```log
[09:39:05] [Server thread/ERROR] [Sponge]: Invalid smelting recipe registration!
The mod "igcm" is registering a smelting recipe wrongly which causes the resulting recipe to be invalid.
A common cause which makes smelting recipes invalid occurs when registering those recipes before the used blocks are
registered, it's recommend to register them when the items are finished registering.

java.lang.IllegalStateException: Invalid smelting recipe registered by the mod "igcm"!
        at net.minecraft.item.crafting.FurnaceRecipes.handler$onAddSmeltingRecipe$zip000(FurnaceRecipes.java:655) [akp.class:?]
        at net.minecraft.item.crafting.FurnaceRecipes.addSmeltingRecipe(FurnaceRecipes.java:119) [akp.class:?]
        at net.minecraft.item.crafting.FurnaceRecipes.addSmelting(FurnaceRecipes.java:111) [akp.class:?]
        at com.creativemd.igcm.machines.FurnaceMachine.addRecipeToList(FurnaceMachine.java:60) [FurnaceMachine.class:?]
        at com.creativemd.igcm.machines.FurnaceMachine.addRecipeToList(FurnaceMachine.java:30) [FurnaceMachine.class:?]
        at com.creativemd.igcm.api.machine.ConfigMachineBranch.onRecieveFrom(ConfigMachineBranch.java:72) [ConfigMachineBranch.class:?
]
        at com.creativemd.igcm.api.machine.ConfigMachineAddBranch.onRecieveFrom(ConfigMachineAddBranch.java:103) [ConfigMachineAddBran
ch.class:?]
        at com.creativemd.igcm.IGCMConfig.loadConfig(IGCMConfig.java:59) [IGCMConfig.class:?]
        at com.creativemd.igcm.IGCM.serverStarting(IGCM.java:158) [IGCM.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.
1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar
:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:
?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar
:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:
?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.
1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar
:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:
?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:797) [Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
I have added the recipes that contain the items from other mod and when I open the GUI their icons are broken (purple and black sqaure grid displayed instead, despite the the recipes still works)

My IGCM data:
[new1.zip](https://github.com/CreativeMD/IGCM/files/3759564/new1.zip)

mods installed:
```
mods/A+Block+of+Charcoal-1.2.jar
mods/AdHooks-1.12.2-3.2.2.0-build.0220.jar
mods/appliedenergistics2-rv6-stable-7.jar
mods/astralsorcery-1.12.2-1.10.20.jar
mods/Atum-1.12.2-2.0.15.jar
mods/AutoRegLib-1.3-32.jar
mods/BattleTowers-1.12.2.jar
mods/Baubles-1.12-1.5.2.jar
mods/Better_Survival-1.3.5.jar
mods/BiblioCraft[v2.4.5][MC1.12.2].jar
mods/Bloodmoon-MC1.12.2-1.5.3.jar
mods/Bookshelf-1.12.2-2.3.585.jar
mods/Botania+r1.10-362.jar
mods/Bountiful+Baubles-1.12.2-0.1.2.jar
mods/CarryOn+MC1.12.2+v1.12.2.jar
mods/CatClearLag-0.9.0.jar
mods/Chisel-MC1.12.2-0.2.1.35.jar
mods/CodeChickenLib-1.12.2-3.2.3.358-universal.jar
mods/CoFHCore-1.12.2-4.6.3.27-universal.jar
mods/CoFHWorld-1.12.2-1.3.1.7-universal.jar
mods/CommonCapabilities-1.12.2-2.4.4.jar
mods/CoralReef-2.5-1.12.2.jar
mods/CraftableHorseArmour-1.3.0-1.12.jar
mods/CraftTweaker2-1.12-4.1.19.jar
mods/CreativeCore_v1.9.68_mc1.12.2.jar
mods/CTM-MC1.12.2-0.3.3.22.jar
mods/CyclopsCore-1.12.2-1.5.0.jar
mods/DarkUtils-1.12.2-1.8.226.jar
mods/defiledlands-1.12.2-1.4.2.jar
mods/DoomlikeDungeons-1.12.10-MC1.12.2.jar
mods/DragonMounts2-1.12.2-1.6.3.jar
mods/extrautils2-1.12-1.9.9.jar
mods/FoodExpansion1.3.3-1.12.2.jar
mods/ForgeEndertech-1.12.2-4.4.24.0-build.0421.jar
mods/Forgelin-1.8.4.jar
mods/future-mc-0.1.11.jar
mods/GlobalGameRules-1.12.2-2.2.7.jar
mods/HuntingDimension-1.12.2-1.0.39.jar
mods/Hwyla-1.8.26-B41_1.12.2.jar
mods/iceandfire-1.8.3.jar
mods/IGCM_v1.2.10_mc1.12.2.jar
mods/ImmersiveEngineering-0.12-92.jar
mods/industrialcraft-2-2.8.170-ex112.jar
mods/InfernalMobs-1.12.2.jar
mods/IntegratedDynamics-1.12.2-1.1.0.jar
mods/IntegratedTunnels-1.12.2-1.6.10.jar
mods/IronBackpacks-1.12.2-3.0.8-12.jar
mods/IvToolkit-1.3.3-1.12.jar
mods/jei_1.12.2-4.15.0.291.jar
mods/llibrary-1.7.19-1.12.2.jar
mods/LootTableTweaker-1.12.2-1.1.14.jar
mods/lostcities-1.12-2.0.21.jar
mods/Mantle-1.12-1.3.3.55.jar
mods/vics_modernwafre2.0-0.4.1_mc1.12.2.jar
mods/nodami-1.12.2-1.2.1.jar
mods/NotEnoughCats-1.12.2-1.2.1.jar
mods/Nucleus-1.12.2-S7.1-MC1.12.2-plugin.jar
mods/OptiFine_1.12.2_HD_U_E3.jar
mods/Placebo-1.12.2-1.6.0.jar
mods/PotionCore-1.8_for_1.12.2.jar
mods/potioncraft-1.1.1.jar
mods/PotionFingers-r1.0-2.jar
mods/QualityTools-1.0.7_for_1.12.2.jar
mods/railcraft-12.0.0.jar
mods/RealBench-1.12.2-1.3.3.jar
mods/RedstoneFlux-1.12-2.1.0.6-universal.jar
mods/Rex's-Additional-Structures-1.12.x-(v.2.3.0).jar
mods/RoguelikeDungeons-1.12.2-1.8.0.jar
mods/ScalingHealth-1.12.2-1.3.40+145.jar
mods/SilentLib-1.12.2-3.0.13+167.jar
mods/slideemall-1.03.jar
mods/somanyenchantments+V0.4.31.jar
mods/SoundFilters-0.11_for_1.12.jar
mods/SpartanShields-1.12.2-1.5.4.jar
mods/SpartanWeaponry-1.12.2-beta-1.3.1.jar
mods/SpawnerControl-1.6.3b.jar
mods/switchbow-1.5.7.jar
mods/TConstruct-1.12.2-2.12.0.157.jar
mods/TheBetweenlands-3.4.12-universal.jar
mods/ThermalExpansion-1.12.2-5.5.4.43-universal.jar
mods/ThermalFoundation-1.12.2-2.6.3.27-universal.jar
mods/ToolBelt-1.12.2-1.9.10.jar
mods/Traverse-1.12.2-1.6.0-69.jar
mods/TreeChopper-1.12.2-1.2.4.jar
mods/twilightforest-1.12.2-3.9.984-universal.jar
mods/unifier-3.0.4.jar
mods/VanillaFix-1.0.10-99.jar
mods/VariedCommodities_1.12.2(15may18.jar
mods/Waystones_1.12.2-4.0.72.jar
mods/VillagerTrades-1.12-0.6.4.jar
mods/WitherSkeletonTweaks-1.12.2-2.6.3.jar
mods/wolfarmor-1.12.2-2.2.3.1798-universal.jar
mods/xpbook-1.12-0.0.3-beta.jar
mods/xpfromharvest-1.12.2-1.1.0.jar
mods/[1.12]MoVillages-1.5.4.jar
mods/Advanced-Fishing-1.12.2-1.3.3.jar
mods/craftablechainmail-1.0.jar
mods/Trinkets+and+Baubles-1.12.2-0.27.jar
mods/lycanitesmobs-1.12.2-2.0.0.12.jar
mods/BuildingGadgets-2.7.3.jar
mods/buildcraft-all-7.99.24.3.jar
```

**Comment by CreativeMD** [comment]
To make it short. I plan to remove the ingame configuration of recipes (crafting table and furnace). It's very hacky and causes way too many issues.

**Comment by SettingDust** [comment]
> To make it short. I plan to remove the ingame configuration of recipes (crafting table and furnace). It's very hacky and causes way too many issues.

Why not CraftTweaker, without hack?

**Comment by CreativeMD** [comment]
IGCM changes recipe while the game is running and not just during the startup like CraftTweaker. That's why it's hacky. Otherwise you would have to restart the game every time you restart.

**Comment by SettingDust** [comment]
> IGCM changes recipe while the game is running and not just during the startup like CraftTweaker. That's why it's hacky. Otherwise you would have to restart the game every time you restart.

If there is not the "hacky". Why not to choose the CraftTweaker. The hot "swap" is the "major" I think

**Comment by CreativeMD** [comment]
I'm very confused ... of course you can use CraftTweaker, I'm just saying that this feature will be removed from IGCM (and that has nothing to do with CraftTweaker).

**Comment by SettingDust** [comment]
> I'm very confused ... of course you can use CraftTweaker, I'm just saying that this feature will be removed from IGCM (and that has nothing to do with CraftTweaker).

Alright. Thanks for patience

**Comment by CreativeMD** [comment]
New version of CreativeCore has been released, IGCM will be abandoned. This repository will be read only.
